export const APP_STORAGE_KEY = 'mission-app:v1';
export const APP_SCHEMA_VERSION = 2;

export type TaxStatus = 'SMALL_SUPPLIER' | 'REGISTERED';

export type MissionStatus = 'DRAFT' | 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'ARCHIVED' | 'CANCELLED';

export type InvoiceStatus = 'GENERATED' | 'SENT' | 'PAID' | 'ARCHIVED' | 'VOIDED';

export type MissionEventType = 'CREATED' | 'UPDATED' | 'STATUS_CHANGED' | 'INVOICE_CREATED' | 'INVOICE_UPDATED';

export type Pharmacien = {
  id: string;
  nom: string;
  opqLicenseNumber?: string;
  opqRegistryId?: string;
  opqStatusLabel?: string;
  opqVerifiedAt?: string;
  adresse: string;
  rue?: string;
  numero?: string;
  ville: string;
  codePostal: string;
  lat?: number;
  lng?: number;
  telephone: string;
  email: string;
  hourlyRateCents: number;
  distanceKmDomicile: number;
  defaultMissionType?: string;
  defaultStartTime?: string;
  defaultEndTime?: string;
  defaultBreakMinutes?: number;
  mealAutoEnabled?: boolean;
  mealThresholdHours?: number;
  mealDefaultCents?: number;
  mileageRateCents?: number;
  taxStatus: TaxStatus;
  gstNumber?: string;
  qstNumber?: string;
  favoritePharmacieId?: string;
  invoiceDueDays?: number;
  paymentTerms?: string;
  isDefaultProfile?: boolean;
};

export type Pharmacie = {
  id: string;
  displayLabel?: string;
  nom: string;
  adresse: string;
  rue?: string;
  numero?: string;
  ville: string;
  codePostal: string;
  lat?: number;
  lng?: number;
  telephone: string;
  email: string;
  defaultBreakMinutes: number;
  defaultMissionType?: string;
  notes?: string;
};

export type DistanceReference = {
  id: string;
  pharmacienId: string;
  pharmacieId: string;
  distanceKm: number;
  distanceAllerKm?: number;
  pharmacienAddressKey?: string;
  pharmacieAddressKey?: string;
  source: 'calculated' | 'manual';
  updatedAt: string;
};

export type OpqPharmacistRegistryEntry = {
  id: string;
  fullName: string;
  licenseNumber?: string | null;
  studentLicenseNumber?: string | null;
  city?: string | null;
  isStudent: boolean;
};

export type OpqPharmacistRegistry = {
  entries: OpqPharmacistRegistryEntry[];
  updatedAt?: string;
  sourceUrl: string;
};

export type AppOptions = {
  missionDefaults: {
    defaultMissionType: string;
    defaultStartTime: string;
    defaultEndTime: string;
    defaultBreakMinutes: number;
    mealAutoEnabled: boolean;
    mealThresholdHours: number;
    mealDefaultCents: number;
    mileageRateCents: number;
  };

  invoiceDefaults: {
    invoiceDueDays: number;
    paymentTerms?: string;
  };

  pdfCalendar: {
    calendarIcsEnabled: boolean;
    calendarReminderMinutes?: number | null;
    pdfFooterEnabled: boolean;
    calendarEventTitle: string;
    calendarReminder: 'NONE' | 'ONE_HOUR' | 'DAY_BEFORE';
  };
};

export type DeductibleExpenseCategory =
  | 'MEAL'
  | 'MILEAGE'
  | 'PARKING'
  | 'TOLL'
  | 'LODGING'
  | 'TRANSPORT'
  | 'SUPPLIES'
  | 'OTHER'
  | 'NON_DEDUCTIBLE';

export type MissionExpense = {
  id: string;
  type?: 'REPAS' | 'KM' | 'AUTRE';
  typeKey: string;
  label: string;
  amountCents: number;
  amount?: number;
  notes?: string;
  billable: boolean;
  createsDeductibleExpense: boolean;
  deductibleCategory: DeductibleExpenseCategory;
  deductibleRate: number;
  distanceKm?: number;
  unitRateCents?: number;
  unitRate?: number;
  quantity?: number;
  receiptIds?: string[];
  source: 'MISSION_EXPENSE';
  missionId?: string;
  missionDayId?: string;
  isAutoGenerated?: boolean;
  isLocked?: boolean;
};

export type ExpenseReceipt = {
  id: string;
  expenseId: string;
  missionId: string;
  missionDayId?: string;
  fileName: string;
  fileType: 'image/jpeg' | 'image/png' | 'application/pdf';
  fileSizeBytes: number;
  storageUrl: string;
  thumbnailUrl?: string;
  uploadedAt: string;
  ocrStatus?: 'NOT_PROCESSED' | 'PROCESSING' | 'PROCESSED' | 'FAILED';
  extractedAmountCents?: number;
  extractedDate?: string;
  extractedMerchant?: string;
  notes?: string;
};

export type MissionDay = {
  id: string;
  dateService: string;
  startTime: string;
  endTime: string;
  unpaidBreakMinutes: number;
  description: string;
  hours: number;
  expenses?: MissionExpense[];
};

export type MissionEvent = {
  id: string;
  eventType: MissionEventType;
  label: string;
  eventDate: string;
};

export type Mission = {
  id: string;
  missionCode: string;
  pharmacienId: string;
  pharmacieId: string;
  status: MissionStatus;
  dateDebut: string;
  dateFin: string;
  days: MissionDay[];
  hourlyRateCents: number;
  mealFeeCents: number;
  mileageKm: number;
  mileageRateCents: number;
  totalHours: number;
  subtotalCents: number;
  mealTotalCents: number;
  mileageTotalCents: number;
  totalCents: number;
  notes?: string;
  invoiceId?: string;
  events: MissionEvent[];
  createdAt: string;
  updatedAt: string;
};

export type Invoice = {
  id: string;
  numero: string;
  missionId: string;
  pharmacienId: string;
  pharmacieId: string;
  dateFacture: string;
  dateEcheance: string;
  status: InvoiceStatus;
  hours: number;
  amountCents: number;
  sentAt?: string;
  paidAt?: string;
  archivedAt?: string;
  createdAt: string;
};

export type DeductibleExpense = {
  id: string;
  date: string;
  label: string;
  category:
    | 'TRAVEL'
    | 'MEAL'
    | 'PARKING'
    | 'SOFTWARE'
    | 'PHONE_INTERNET'
    | 'PROFESSIONAL_FEES'
    | 'INSURANCE'
    | 'ACCOUNTING'
    | 'TRAINING'
    | 'OFFICE'
    | 'OTHER';
  amountCents: number;
  taxDeductible: boolean;
  hasReceipt?: boolean;
  notes?: string;
};

export type TaxPayment = {
  id: string;
  date: string;
  period: string;
  authority: 'CRA' | 'REVENU_QUEBEC';
  type: 'INCOME_TAX_INSTALMENT' | 'GST_QST_REMITTANCE' | 'OTHER';
  amountCents: number;
  reference?: string;
  notes?: string;
};

export type FiscalSettings = {
  reserveRate: number;
  fiscalYearStartMonth: number;
  currentFiscalYear: number;
  smallSupplierThresholdCents: number;
  smallSupplierWarningRate: number;
  instalmentDates: string[];
  quebecNetTaxOwingThresholdCents: number;
  federalNetTaxOwingThresholdCents: number;
  federalDefaultNetTaxOwingThresholdCents: number;
  mileageRateCents?: number;
  currentYear: number;
  defaultTaxStatus: TaxStatus;
  includeMissionDeductibleExpenses: boolean;
  trackExpenseReceipts: boolean;
  warnMissingExpenseReceipts: boolean;
  showMonthlyView: boolean;
  showQuarterlyView: boolean;
  showAnnualView: boolean;
  enableInstalmentTracking: boolean;
  enableSmallSupplierTracking: boolean;
  enableExpenseTracking: boolean;
  mealDeductibleRate?: number;
  mileageDeductibleRate?: number;
  parkingDeductibleRate?: number;
  tollDeductibleRate?: number;
  lodgingDeductibleRate?: number;
  transportDeductibleRate?: number;
  suppliesDeductibleRate?: number;
  otherNonDeductibleRate?: number;
};

export type UiSettings = {
  themeMode: 'light' | 'dark' | 'system';
  primaryColor?: string;
  secondaryColor?: string;
};

export type LocalDataSettings = {
  autoBackupEnabled: boolean;
};

export type AppState = {
  version: 2;
  activePharmacienId: string | null;
  pharmaciens: Pharmacien[];
  pharmacies: Pharmacie[];
  missions: Mission[];
  invoices: Invoice[];
  taxPayments: TaxPayment[];
  deductibleExpenses: DeductibleExpense[];
  expenseReceipts: ExpenseReceipt[];
  fiscalSettings: FiscalSettings;
  distanceReferences: DistanceReference[];
  opqPharmacistRegistry: OpqPharmacistRegistry;
  appOptions: AppOptions;
  uiSettings: UiSettings;
  localDataSettings: LocalDataSettings;
  ui: {
    missionFilters: Record<string, unknown>;
    lastVisitedAt?: string;
  };
};
